# Generated by Django 5.1.4 on 2025-02-08 16:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Realtor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('designation', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Realtor',
                'verbose_name_plural': 'Realtors',
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_1', models.CharField(max_length=255)),
                ('address_2', models.CharField(blank=True, max_length=255, null=True)),
                ('address_3', models.CharField(blank=True, max_length=255, null=True)),
                ('address_4', models.CharField(blank=True, max_length=50, null=True)),
                ('title', models.CharField(max_length=255)),
                ('condition', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=50)),
                ('taxes', models.CharField(max_length=50)),
                ('features', models.JSONField()),
                ('main_image', models.URLField(max_length=1500)),
                ('client_remark', models.TextField()),
                ('extras', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('realtor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='mlsreport2.realtor')),
            ],
            options={
                'verbose_name': 'Property',
                'verbose_name_plural': 'Properties',
            },
        ),
        migrations.CreateModel(
            name='ListingInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pin_number', models.CharField(max_length=100)),
                ('taxes', models.CharField(max_length=50)),
                ('tax_year', models.CharField(max_length=10)),
                ('legal_description', models.TextField()),
                ('status', models.CharField(max_length=50)),
                ('possession_remarks', models.CharField(blank=True, max_length=255, null=True)),
                ('seller_info', models.CharField(max_length=10)),
                ('property', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='listing_info', to='mlsreport2.property')),
            ],
            options={
                'verbose_name': 'Listing Information',
                'verbose_name_plural': 'Listing Information',
            },
        ),
        migrations.CreateModel(
            name='PropertyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approx_age', models.CharField(max_length=50)),
                ('fronting_on', models.CharField(max_length=50)),
                ('lot_size', models.CharField(max_length=100)),
                ('square_feet', models.CharField(max_length=50)),
                ('drive', models.CharField(max_length=100)),
                ('total_parking_spaces', models.IntegerField()),
                ('pool', models.CharField(blank=True, max_length=50, null=True)),
                ('air_conditioning', models.CharField(max_length=50)),
                ('heating_source', models.CharField(max_length=50)),
                ('heating_type', models.CharField(max_length=50)),
                ('water', models.CharField(max_length=50)),
                ('sewers', models.CharField(max_length=50)),
                ('property', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='property_info', to='mlsreport2.property')),
            ],
            options={
                'verbose_name': 'Property Information',
                'verbose_name_plural': 'Property Information',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('level', models.CharField(max_length=50)),
                ('dimensions', models.JSONField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='mlsreport2.property')),
            ],
            options={
                'verbose_name': 'Room',
                'verbose_name_plural': 'Rooms',
            },
        ),
        migrations.CreateModel(
            name='Washroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pieces', models.IntegerField()),
                ('level', models.CharField(max_length=50)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='washrooms', to='mlsreport2.property')),
            ],
            options={
                'verbose_name': 'Washroom',
                'verbose_name_plural': 'Washrooms',
            },
        ),
    ]
