# Generated by Django 5.1.4 on 2025-02-19 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlsreport2', '0002_propertyinfo_hst_applicable_to_sale_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyinfo',
            name='water_front',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='propertyinfo',
            name='HST_applicable_to_sale_price',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='propertyinfo',
            name='area',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='propertyinfo',
            name='basement',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='propertyinfo',
            name='bedrooms',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='propertyinfo',
            name='community',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='propertyinfo',
            name='dir_cross_st',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='propertyinfo',
            name='exteriors',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='propertyinfo',
            name='foundation',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='propertyinfo',
            name='garage_parking_spaces',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='propertyinfo',
            name='garage_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='propertyinfo',
            name='kitchens',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='propertyinfo',
            name='laundary_level',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='propertyinfo',
            name='lot_size_source',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='propertyinfo',
            name='municipality',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='propertyinfo',
            name='parking_drive_space',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='propertyinfo',
            name='roof',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='propertyinfo',
            name='rooms',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='propertyinfo',
            name='washrooms',
            field=models.CharField(max_length=50),
        ),
    ]
